package uq.pac.rsvp.policy.datalog.translation;

import com.cedarpolicy.model.exception.AuthException;
import uq.pac.rsvp.RsvpException;
import uq.pac.rsvp.policy.datalog.ast.DLProgram;
import uq.pac.rsvp.policy.datalog.ast.DLRuleDecl;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Stream;

import static uq.pac.rsvp.policy.datalog.translation.RequestAuth.Decision.*;
import static uq.pac.rsvp.policy.datalog.util.Assertion.require;

/**
 * A class representing a request authentication engine that checks whether a
 * given request is permitted, forbidden or inconclusive.
 * <p>
 * For the moment, internally, this engine tracks sets of forbidden
 * and permitted requests loaded from Datalog.
 */
public class RequestAuth {
    /**
     * Permitted requests
     */
    private final RequestSet permitted;
    /**
     * Forbidden requests
     */
    private final RequestSet forbidden;
    /**
     * Per-policy permitted requests
     */
    private final List<RequestSet> permitPolicies;
    /**
     * Per-policy forbidden requests
     */
    private final List<RequestSet> forbidPolicies;

    private RequestAuth(RequestSet permitted, RequestSet forbidden,
                        List<RequestSet> permitPolicies, List<RequestSet> forbidPolicies) {
        this.permitted = permitted;
        this.forbidden = forbidden;
        this.permitPolicies = permitPolicies;
        this.forbidPolicies = forbidPolicies;

        // Permitted and forbidden are disjoint sets
        permitted.forEach(s -> require(!forbidden.contains(s)));
    }

    public enum Decision {
        Allow,
        Deny,
        Invalid
    }

    public Decision authorize(Request request) {
        if (permitted.contains(request)) {
            return Allow;
        } else if (forbidden.contains(request)) {
            return Deny;
        }
        return Invalid;
    }

    private static RequestSet loadRequests(Path dir, DLRuleDecl decl) {
        Path csv = Path.of(decl.getName() + TranslationConstants.OUTPUT_EXT);
        return loadRequests(dir, csv, decl.getName());
    }

    // Load requests generated by the {@code decl} rule declaration
    // from a datalog specification stored in the {@code dir} directory.
    private static RequestSet loadRequests(Path dir, Path csv, String name) {
        Path dlOut = Path.of(dir.toString(), csv.getFileName().toString());
        if (!Files.exists(dlOut)) {
            throw new TranslationError("Target CSV file %s does not exist or not a directory".formatted(dlOut));
        }

        BufferedReader reader;
        Set<Request> set = new HashSet<>();
        try {
            reader = new BufferedReader(new FileReader(dlOut.toFile()));
            String line = reader.readLine();
            while (line != null) {
                set.add(new Request(line.trim()));
                line = reader.readLine();
            }
            reader.close();
        } catch (IOException e) {
            throw new TranslationError(e.getMessage());
        }
        return new RequestSet(set, name);
    }

    public static RequestAuth load(Path schema, Path policies, Path entities, Path invariants, Path dlDir) throws AuthException, IOException, InterruptedException, RsvpException {
        DLProgram program = Translation.translate(schema, policies, entities, invariants);
        program.execute(dlDir);
        return RequestAuth.load(dlDir);
    }

    private static RequestAuth load(Path dir) {
        if (!Files.exists(dir) ||  !Files.isDirectory(dir)) {
            throw new TranslationError("Target directory %s does not exist or not a directory".formatted(dir));
        }

        RequestSet permitted = loadRequests(dir, TranslationConstants.PermittedRequestsRuleDecl);
        RequestSet forbidden = loadRequests(dir, TranslationConstants.ForbiddenRequestsRuleDecl);

        List<RequestSet> permitPolicies = new ArrayList<>(),
                forbidPolicies = new ArrayList<>();

        try (Stream<Path> files = Files.list(dir)) {
            files.filter(Files::isRegularFile)
                    .map(TranslationConstants::getOutputPolicyName)
                    .filter(Objects::nonNull)
                    .forEach(fn -> {
                        List<RequestSet> target = fn.permit() ? permitPolicies : forbidPolicies;
                        target.add(loadRequests(dir, fn.csv(), fn.name()));
                    });
        } catch (IOException e) {
            throw new TranslationError(e.getMessage());
        }
        return new RequestAuth(permitted, forbidden,
                List.copyOf(permitPolicies),
                List.copyOf(forbidPolicies));
    }

    public RequestSet getPermittedRequests() {
        return permitted;
    }

    public RequestSet getForbiddenRequests() {
        return forbidden;
    }

    public Collection<RequestSet> getPermitPolicies() {
        return permitPolicies;
    }

    public Collection<RequestSet> getForbidPolicies() {
        return forbidPolicies;
    }

    public Set<Request> getActionableRequests() {
        Set<Request> requests = new HashSet<>();
        requests.addAll(getPermittedRequests().getRequests());
        requests.addAll(getForbiddenRequests().getRequests());
        return requests;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Permitted: \n");
        for (Request p : permitted.getRequests()) {
            sb.append("   ").append(p.toString()).append('\n');
        }
        return sb.toString();
    }
}
