package uq.pac.rsvp.policy.datalog.translation;

import com.cedarpolicy.model.exception.AuthException;
import uq.pac.rsvp.policy.datalog.ast.DLProgram;
import uq.pac.rsvp.policy.datalog.ast.DLRuleDecl;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.Set;

import static uq.pac.rsvp.policy.datalog.translation.RequestAuth.Result.*;
import static uq.pac.rsvp.policy.datalog.util.Assertion.require;

/**
 * A class representing a request authentication engine that checks whether a
 * given request is permitted, forbidden or inconclusive.
 * <p>
 * For the moment, internally, this engine tracks sets of forbidden
 * and permitted requests loaded from Datalog.
 */
public class RequestAuth {

    /**
     * Permitted requests
     */
    private final Set<Request> permitted;
    /**
     * Forbidden requests
     */
    private final Set<Request> forbidden;
    /**
     * A universe of all requests that could be constructed of entities and actions.
     * Not all of them are necessarily valid from the perspective of the schema and policies.
	 * For instance, a request using a principal type that goes against the policy is considered
     * invalid is cedar
     */
    private final Set<Request> universe;

    private RequestAuth(Set<Request> universe, Set<Request> permitted, Set<Request> forbidden) {
        this.universe = universe;
        this.permitted = permitted;
        this.forbidden = forbidden;

        // Permitted and forbidden are disjoint sets
        permitted.forEach(s -> require(!forbidden.contains(s)));
        // Permitted and forbidden sets should be in the universe of potential requests
        require(universe.containsAll(permitted));
        require(universe.containsAll(forbidden));
    }

    public enum Result {
        Allow,
        Deny,
        Invalid
    }

    public Result authorize(Request request) {
        if (permitted.contains(request)) {
            return Allow;
        } else if (universe.contains(request)) {
            return Deny;
        }
        return Invalid;
    }

    // Load requests generated by the {@code decl} rule declaration
    // from a datalog specification stored in the {@code dir} directory.
    private static Set<Request> loadRequests(Path dir, DLRuleDecl decl) {
        Path csv = Path.of(dir.toString(), decl.getName() + ".csv");
        if (!Files.exists(csv)) {
            throw new TranslationError("Target CSV file %s does not exist or not a directory".formatted(csv));
        }

        BufferedReader reader;
        Set<Request> set = new HashSet<>();
        try {
            reader = new BufferedReader(new FileReader(csv.toFile()));
            String line = reader.readLine();
            while (line != null) {
                set.add(new Request(line.trim()));
                line = reader.readLine();
            }
            reader.close();
        } catch (IOException e) {
            throw new TranslationError(e.getMessage());
        }
        return set;
    }

    public static RequestAuth load(Path schema, Path policies, Path entities, Path dlDir) throws AuthException, IOException, InterruptedException {
        DLProgram program = Translation.translate(schema, policies, entities);
        program.execute(dlDir);
        return RequestAuth.load(dlDir);
    }

    private static RequestAuth load(Path dir) {
        if (!Files.exists(dir) ||  !Files.isDirectory(dir)) {
            throw new TranslationError("Target directory %s does not exist or not a directory".formatted(dir));
        }
        Set<Request> universe = loadRequests(dir, TranslationConstants.AllRequestsRuleDecl);
        Set<Request> permitted = loadRequests(dir, TranslationConstants.PermittedRequestsRuleDecl);
        Set<Request> forbidden = loadRequests(dir, TranslationConstants.ForbiddenRequestsRuleDecl);
        return new RequestAuth(universe, permitted, forbidden);
    }

    public Set<Request> getPermittedRequests() {
        return permitted;
    }

    public Set<Request> getForbiddenRequests() {
        return forbidden;
    }

    public Set<Request> getActionableRequests() {
        Set<Request> requests = new HashSet<>();
        requests.addAll(getPermittedRequests());
        requests.addAll(getForbiddenRequests());
        return requests;
    }

    public Set<Request> getRequestUniverse() {
        return universe;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Permitted: \n");
        for (Request p : permitted) {
            sb.append("   ").append(p.toString()).append('\n');
        }
        return sb.toString();
    }
}
