DROP TABLE clinics IF EXISTS;
DROP TABLE entities IF EXISTS;
DROP TABLE entity_types IF EXISTS;
DROP TABLE entity_clinics IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE genders IF EXISTS;
DROP TABLE persons IF EXISTS;
DROP TABLE administrative_assistants IF EXISTS;
DROP TABLE doctors IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE doctor_specialties IF EXISTS;
DROP TABLE roles IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE levels IF EXISTS;
DROP TABLE user_levels IF EXISTS;
DROP TABLE user_manager IF EXISTS;
DROP TABLE adults IF EXISTS;
DROP TABLE patients IF EXISTS;
DROP TABLE authorities IF EXISTS;
DROP TABLE patient_adults IF EXISTS;
DROP TABLE confidentialities IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE visit_adults IF EXISTS;
DROP TABLE patient_doctors IF EXISTS;
DROP TABLE visit_doctors IF EXISTS;

-- Lookup Clinics Table.
CREATE TABLE clinics (
  clinic_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40) UNIQUE NOT NULL
);
CREATE INDEX clinics_name ON clinics (name);

-- Super-Table.
CREATE SEQUENCE entities_sequence START WITH 1 INCREMENT BY 1;
CREATE TABLE entities (
  entity_id  INTEGER DEFAULT NEXT VALUE FOR entities_sequence PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entity_types (
  entity_id   INTEGER NOT NULL,
  entity_type VARCHAR(40) NOT NULL, -- 'User', 'Administrator', 'Assistant', 'Doctor', 'Adult', 'Patient', 'Visit'.
  PRIMARY KEY (entity_id, entity_type),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);

CREATE TABLE entity_clinics (
  entity_id  INTEGER NOT NULL,
  clinic_id  INTEGER NOT NULL,
  PRIMARY KEY (entity_id, clinic_id),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (clinic_id) REFERENCES clinics(clinic_id) ON DELETE CASCADE
);

CREATE TABLE users (
  entity_id  INTEGER PRIMARY KEY,
  username   VARCHAR(80) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX users_username ON users (username);

-- Lookup Genders Table.
CREATE TABLE genders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40)
);
CREATE INDEX genders_name ON genders (name);

CREATE TABLE persons (
  entity_id  INTEGER PRIMARY KEY,
  first_name VARCHAR(40) NOT NULL,
  last_name  VARCHAR(40) NOT NULL,
  birth_date DATE NOT NULL,
  gender_id  INTEGER NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (gender_id) REFERENCES genders(id) ON DELETE CASCADE,
  CONSTRAINT unique_person UNIQUE (first_name, last_name, birth_date, gender_id)
);
CREATE INDEX persons_last_name ON persons (last_name);

CREATE TABLE administrative_assistants (
  entity_id  INTEGER PRIMARY KEY,
  telephone  VARCHAR(20) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES persons(entity_id) ON DELETE CASCADE
);

CREATE TABLE doctors (
  entity_id  INTEGER PRIMARY KEY,
  telephone  VARCHAR(20) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES persons(entity_id) ON DELETE CASCADE
);

-- Lookup Specialties Table.
CREATE TABLE specialties (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40) UNIQUE NOT NULL
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE doctor_specialties (
  doctor_id    INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL,
  PRIMARY KEY (doctor_id, specialty_id),
  FOREIGN KEY (doctor_id) REFERENCES doctors(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

-- Lookup Employee Role Table.
CREATE TABLE roles (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40) UNIQUE NOT NULL
);
CREATE INDEX roles_name ON roles (name);

CREATE TABLE user_roles (
  user_id    INTEGER NOT NULL,
  role_id    INTEGER NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Lookup Professional Level Table.
CREATE TABLE levels (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40) UNIQUE NOT NULL
);
CREATE INDEX levels_name ON levels (name);

CREATE TABLE user_levels (
  user_id    INTEGER NOT NULL,
  level_id   INTEGER NOT NULL,
  PRIMARY KEY (user_id, level_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE
);

CREATE TABLE user_manager (
  user_id    INTEGER NOT NULL,
  manager_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, manager_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (manager_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  CONSTRAINT distinct_users CHECK (user_id != manager_id)
);

CREATE TABLE adults (
  entity_id  INTEGER PRIMARY KEY,
  telephone  VARCHAR(20) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES persons(entity_id) ON DELETE CASCADE
);

CREATE TABLE patients (
  entity_id  INTEGER PRIMARY KEY,
  address    VARCHAR(240) NOT NULL,
  city       VARCHAR(40) NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES persons(entity_id) ON DELETE CASCADE
);

CREATE TABLE authorities (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40)
);
CREATE INDEX authorities_name ON authorities (name);

CREATE TABLE patient_adults (
  patient_id   INTEGER NOT NULL,
  adult_id     INTEGER NOT NULL,
  authority_id INTEGER NOT NULL,
  PRIMARY KEY (patient_id, adult_id),
  FOREIGN KEY (patient_id) REFERENCES patients(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (adult_id) REFERENCES adults(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (authority_id) REFERENCES authorities(id) ON DELETE CASCADE
);

-- Lookup Confidentialities Table.
CREATE TABLE confidentialities (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40)
);
CREATE INDEX confidentialities_name ON confidentialities (name);

CREATE TABLE visits (
  entity_id          INTEGER PRIMARY KEY,
  patient_id         INTEGER NOT NULL,
  visit_date         DATE NOT NULL,
  confidentiality_id INTEGER NOT NULL,
  description VARCHAR(320),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (patient_id) REFERENCES patients(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (confidentiality_id) REFERENCES confidentialities(id) ON DELETE CASCADE
);
CREATE INDEX visits_patient_id ON visits (patient_id);

CREATE TABLE visit_adults (
  visit_id   INTEGER NOT NULL,
  adult_id   INTEGER NOT NULL,
  PRIMARY KEY (visit_id, adult_id),
  FOREIGN KEY (visit_id) REFERENCES visits(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (adult_id) REFERENCES adults(entity_id) ON DELETE CASCADE
);

CREATE TABLE patient_doctors (
  patient_id INTEGER NOT NULL,
  doctor_id  INTEGER NOT NULL,
  PRIMARY KEY (patient_id, doctor_id),
  FOREIGN KEY (patient_id) REFERENCES patients(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (doctor_id) REFERENCES doctors(entity_id) ON DELETE CASCADE
);

CREATE TABLE visit_doctors (
  visit_id   INTEGER NOT NULL,
  doctor_id  INTEGER NOT NULL,
  PRIMARY KEY (visit_id, doctor_id),
  FOREIGN KEY (visit_id) REFERENCES visits(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (doctor_id) REFERENCES doctors(entity_id) ON DELETE CASCADE
);
