/*
 * This source file was generated by the Gradle 'init' task
 */
package policygen;

import java.io.FileOutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Random;
import java.util.Set;

import com.cedarpolicy.model.entity.Entities;

import policygen.entity.Entity;
import policygen.entity.EntityImpl;
import policygen.entity.FileResource;
import policygen.entity.Folder;
import policygen.entity.Group;
import policygen.entity.User;
import uq.pac.rsvp.policy.ast.expr.BinaryExpression;
import uq.pac.rsvp.policy.ast.expr.BooleanExpression;
import uq.pac.rsvp.policy.ast.expr.EntityExpression;
import uq.pac.rsvp.policy.ast.expr.Expression;
import uq.pac.rsvp.policy.ast.expr.LongExpression;
import uq.pac.rsvp.policy.ast.expr.PropertyAccessExpression;
import uq.pac.rsvp.policy.ast.expr.RecordExpression;
import uq.pac.rsvp.policy.ast.expr.StringExpression;
import uq.pac.rsvp.policy.ast.expr.UnaryExpression;
import uq.pac.rsvp.policy.ast.expr.VariableExpression;
import uq.pac.rsvp.policy.ast.schema.ActionDefinition;
import uq.pac.rsvp.policy.ast.schema.CommonTypeDefinition;
import uq.pac.rsvp.policy.ast.schema.EntityTypeDefinition;
import uq.pac.rsvp.policy.ast.schema.Schema;
import uq.pac.rsvp.policy.ast.schema.common.BooleanType;
import uq.pac.rsvp.policy.ast.schema.common.CommonTypeReference;
import uq.pac.rsvp.policy.ast.schema.common.EntityTypeReference;
import uq.pac.rsvp.policy.ast.schema.common.LongType;
import uq.pac.rsvp.policy.ast.schema.common.RecordTypeDefinition;
import uq.pac.rsvp.policy.ast.schema.common.StringType;
import uq.pac.rsvp.policy.ast.visitor.SchemaVisitor;
import uq.pac.rsvp.policy.ast.visitor.SchemaVisitorImpl;

public class App {

    private static Random random = new Random();

    public static void main(String[] args) throws Exception {

        SchemaWrapper schema = null;
        EntityPool pool = null;

        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--schema")) {
                i++;
                if (i == args.length) {
                    System.err.println("Error: '--schema' requires an argument");
                    System.exit(1);
                }
                Path schemaPath = Path.of(args[i]);
                Schema theSchema = Schema.parseCedarSchema(schemaPath);

                SchemaWrapper[] resultSchemaWrapper = new SchemaWrapper[1];
                SchemaVisitor visitor = new SchemaVisitorImpl() {

                    Map<EntityTypeDefinition, CedarEntityRef> entityTypes = new HashMap<>();
                    List<CedarAction> actions = new ArrayList<>();

                    private CedarType mapType(CommonTypeDefinition ctd) {
                        CedarType[] resultType = new CedarType[1];
                        ctd.accept(new SchemaVisitorImpl() {
                            @Override
                            public void visitBoolean(BooleanType type) {
                                resultType[0] = CedarPrimitive.BOOL;
                            }

                            @Override
                            public void visitLong(LongType type) {
                                resultType[0] = CedarPrimitive.LONG;
                            }

                            @Override
                            public void visitString(StringType type) {
                                resultType[0] = CedarPrimitive.STRING;
                            }

                            @Override
                            public void visitCommonTypeReference(CommonTypeReference type) {
                                // TODO Auto-generated method stub
                                //visitCommonTypeReference(type);
                                System.out.println("*** " + type.getName());
                                if (type.getDefinition() == null) {
                                    System.out.println("*** definition is null");
                                }
                                type.getDefinition().accept(this);
                            }

                            @Override
                            public void visitEntityTypeReference(EntityTypeReference type) {
                                String entityTypeName = type.getDefinition().getName();
                                CedarEntityRef entityRef = entityTypes.computeIfAbsent(type.getDefinition(),
                                        k -> new CedarEntityRef(entityTypeName));
                                resultType[0] = entityRef;
                            }

                            @Override
                            public void visitRecordTypeDefinition(RecordTypeDefinition rtd) {
                                Set<String> attrNames = rtd.getAttributeNames();
                                CedarField[] fields = new CedarField[attrNames.size()];

                                int i = 0;
                                for (String attrName : attrNames) {
                                    fields[i++] = new CedarField(attrName, mapType(rtd.getAttributeType(attrName)));
                                }

                                resultType[0] = new CedarRecord(fields);
                            }
                        });

                        if (resultType[0] == null)
                            throw new UnsupportedOperationException("Unhandled type in schema: " + ctd);

                        return resultType[0];
                    }

                    @Override
                    public void visitEntityTypeDefinition(EntityTypeDefinition etd) {
                        // etd.getEntityNamesEnum()
                        // etd.getMemberOfTypes()
                        String entityTypeName = etd.getName();

                        // Create the type now in case of recursive definition (attributes of
                        // entity type), or retrieve the existing (empty) entity in case it has
                        // been referenced previously:
                        CedarEntityRef entityRef = entityTypes.computeIfAbsent(etd,
                                k -> new CedarEntityRef(entityTypeName));

                        Set<String> attrNames = etd.getShapeAttributeNames();
                        CedarField[] fields = new CedarField[attrNames.size()];

                        int i = 0;
                        for (String attrName : attrNames) {
                            fields[i++] = new CedarField(attrName, mapType(etd.getShapeAttributeType(attrName)));
                        }

                        entityRef.setFields(fields);

                        Set<EntityTypeDefinition> memberOfETDs = etd.getMemberOfTypes();
                        List<CedarEntityRef> memberOfTypes = new ArrayList<>();
                        for (EntityTypeDefinition parentETD : memberOfETDs) {
                            CedarEntityRef parentRef = entityTypes.computeIfAbsent(parentETD,
                                    k -> new CedarEntityRef(parentETD.getName()));
                            memberOfTypes.add(parentRef);
                        }

                        entityRef.setParentTypes(memberOfTypes);
                    }

                    @Override
                    public void visitActionDefinition(ActionDefinition action) {

                        // Actions:
                        // - May apply to a context (record) type
                        // - Apply to specific principal type(s)
                        // - Apply to specific resource type(s)
                        List<CedarEntityRef> principals = new ArrayList<>();
                        for (EntityTypeDefinition etd : action.getAppliesToPrincipalTypes()) {
                            CedarEntityRef entityRef = entityTypes.computeIfAbsent(etd,
                                    k -> new CedarEntityRef(etd.getName()));
                            principals.add(entityRef);
                        }

                        List<CedarEntityRef> resources = new ArrayList<>();
                        for (EntityTypeDefinition etd : action.getAppliesToResourceTypes()) {
                            CedarEntityRef entityRef = entityTypes.computeIfAbsent(etd,
                                    k -> new CedarEntityRef(etd.getName()));
                            resources.add(entityRef);
                        }

                        CedarRecord context = null;
                        if (action.getAppliesToContext() != null) {
                            context = (CedarRecord) mapType(action.getAppliesToContext());
                        }

                        CedarAction newAction = new CedarAction(action.getName(), principals, resources, context);
                        actions.add(newAction);
                    }

                    @Override
                    public void visitSchema(Schema schema) {
                        super.visitSchema(schema);
                        resultSchemaWrapper[0] = new SchemaWrapperImpl(entityTypes.values(), actions);
                    }
                };

                visitor.visitSchema(theSchema);
                schema = resultSchemaWrapper[0];
            } else if (args[i].equals("--entities")) {
                i++;
                if (i == args.length) {
                    System.err.println("Error: '--entities' requires an argument");
                    System.exit(1);
                }

                pool = new EntityPool();
                Entities entities = Entities.parse(Path.of(args[i]));
                for (com.cedarpolicy.model.entity.Entity entity : entities.getEntities()) {
                    pool.addEntity(new EntityImpl(entity.getEUID().getType().toString(), entity.getEUID().getId().toString()));
                }
            } else {
                System.err.println("Error: unrecognised argument '" + args[i] + "'.");
                System.exit(1);
            }
        }

        if (schema == null) {
            pool = getDefaultEntityPool();
            schema = new SchemaWrapperDefault();
        } else if (pool == null) {
            System.err.println("Error: schema provided without entity pool.");
            System.exit(1);
        }

        try (FileOutputStream policyOutFS = new FileOutputStream("policy-out.cedar")) {
            PrintStream policyOut = new PrintStream(policyOutFS);
            for (int i = 0; i < 100; i++) {
                generatePolicy(policyOut, pool, schema);
            }
        }
    }

    private static EntityPool getDefaultEntityPool() {
        Group adminGroup = new Group("Admins", null);
        Group staffGroup = new Group("Staff", null);
        Group seniorStaffGroup = new Group("SeniorStaff", staffGroup);

        ArrayList<User> userList;
        ArrayList<Group> groupList;
        ArrayList<Folder> folderList;
        ArrayList<FileResource> fileList;

        groupList = new ArrayList<>();
        groupList.add(adminGroup);
        groupList.add(staffGroup);
        groupList.add(seniorStaffGroup);

        userList = new ArrayList<>();
        userList.add(new User("Joe", 25, 5, adminGroup));
        userList.add(new User("Sally", 33, 7, staffGroup));
        userList.add(new User("Matumbah", 56, 3, seniorStaffGroup));
        userList.add(new User("Philip", 21, 3, null /* no group */));

        folderList = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            folderList.add(new Folder(null));
        }

        fileList = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            Folder parent = folderList.get(random.nextInt(folderList.size()));
            fileList.add(new FileResource(parent));
        }

        EntityPool pool = new EntityPool();
        groupList.forEach(g -> pool.addEntity(g));
        userList.forEach(u -> pool.addEntity(u));
        folderList.forEach(f -> pool.addEntity(f));
        fileList.forEach(f -> pool.addEntity(f));

        return pool;
    }

    private static boolean randomChance(int percent) {
        return random.nextInt(100) < percent;
    }

    /**
     * Given an entity type, get all the entity types that can be an ancestor of the type.
     */
    private static Collection<CedarEntityRef> getAncestorTypes(CedarEntityRef entityType) {
        Set<CedarEntityRef> allAncestors = new HashSet<>();
        List<CedarEntityRef> queue = new LinkedList<>();
        queue.add(entityType);

        while (!queue.isEmpty()) {
            CedarEntityRef first = queue.removeFirst();
            for (CedarEntityRef parentType : first.getParentTypes()) {
                if (allAncestors.add(parentType)) {
                    queue.add(parentType);
                }
            }
        }

        return allAncestors;
    }

    private static void generatePolicy(PrintStream output, EntityPool entities, SchemaWrapper schema) {
        // "permit" or "forbid"?
        // 60% permit
        boolean isPermit = randomChance(60);
        String policyStr = isPermit ? "permit (\n" : "forbid (\n";

        // Need principal, action, resource, conditions
        String principal = randomPrincipal(entities, schema);
        policyStr += "    " + principal + ",\n";

        String action = randomAction(schema);
        policyStr += "    " + action + ",\n";

        String resource = randomResource(entities, schema);
        policyStr += "    " + resource + "\n";

        policyStr += ")";

        int conditionChance = 70;
        while (randomChance(conditionChance)) {
            policyStr += "\n" + generateCondition(entities, schema);
            conditionChance = 25; // reduced chance of additional conditions
        }

        policyStr += ";\n";
        output.println(policyStr);
    }

    private static String randomPrincipal(EntityPool entities, SchemaWrapper schema) {
        return randomMultiple("principal", schema.getPrincipalType(), entities, schema);
    }

    private static String randomResource(EntityPool entities, SchemaWrapper schema) {
        return randomMultiple("resource", schema.getResourceType(), entities, schema);
    }

    private static String randomMultiple(String varName, CedarEntityRef entityType,
            EntityPool entities, SchemaWrapper schema) {
        // Can be a specific principal ('principal == User::"boo_radley"'), an "is" clause
        // (type check),  or a membership check ('principal in Group::"fun_llamas"') optionally
        // combined with "is" clause

        // TODO: generate "is" clauses.

        int principalForm = random.nextInt(100);
        if (principalForm >= 50) {
            Collection<CedarEntityRef> ancestorTypes = getAncestorTypes(entityType);
            if (!ancestorTypes.isEmpty()) {
                int chosenIndex = random.nextInt(ancestorTypes.size());
                Iterator<CedarEntityRef> iter = ancestorTypes.iterator();
                for (int i = 0; i < chosenIndex; i++)
                    iter.next();
                CedarEntityRef chosenType = iter.next();
                Entity chosenEntity = entities.getRandomEntityOfType(chosenType, random);
                return varName + " in " + chosenEntity.toEntityString();
            }
            principalForm -= 50; // reduce to [0, 50)
        }

        if (principalForm < 25) {
            return varName;
        }

        // else (principalForm < 50)
        Entity entity = entities.getRandomEntityOfType(entityType, random);
        if (entity == null) {
            // No known entities of the given type, so can't constrain
            // TODO maybe convert to "is"?
            return varName;
        }
        return varName + " == " + entity.toEntityString();
    }

    private static String randomAction(SchemaWrapper schema) {
        // FIXME make sure to use actions applicable to the principal/resource
        List<CedarAction> actions = schema.getActions();
        int actionIndex = random.nextInt(actions.size() + 1);
        if (actionIndex == actions.size()) {
            return "action"; // no constraint
        }
        return "action == " + actions.get(actionIndex).getName();
    }

    private static class ExpressionWithType {
        Expression expression;
        CedarType exprType;
    }

    /**
     * Generate an expression with a value of arbitrary type.
     */
    private static ExpressionWithType generateValueExpr(EntityPool entities, SchemaWrapper schema,
            boolean allowLiterals) {

        Expression valueExpr = null;
        CedarType valueType = null;

        int valueTypeIndex = random.nextInt(100);
        // 35% principal, 35% resources, 30% context
        if (valueTypeIndex >= 70) {
            // context
            valueType = schema.getRequestType();
            if (valueType != null) {
                valueExpr = VariableExpression.createContextRef(null);
            }
            valueTypeIndex = random.nextInt(70);
        }

        if (valueTypeIndex < 35) {
            // principal.
            valueExpr = VariableExpression.createPrincipalRef(null);
            valueType = schema.getPrincipalType();
        }
        else if (valueTypeIndex < 70) {
            // resource
            valueExpr = VariableExpression.createResourceRef(null);
            valueType = schema.getResourceType();
        }

        // Potentially drill down, i.e. select a field
        while (randomChance(80)) {
            if (valueType.getTypeId() != CedarType.TypeId.ENTITY
                    && valueType.getTypeId() != CedarType.TypeId.RECORD)
                break;

            Map<String, CedarType> fields = valueType.getFields();

            if (!fields.isEmpty()) {
                // Choose a field at random:
                int fieldIndex = random.nextInt(fields.size());
                Iterator<Entry<String, CedarType>> it = fields.entrySet().iterator();
                while (fieldIndex > 0) {
                    it.next();
                    fieldIndex--;
                }
                Entry<String, CedarType> entry = it.next();

                valueExpr = new PropertyAccessExpression(valueExpr, entry.getKey(), null);
                valueType = entry.getValue();
            }
        }

        ExpressionWithType result = new ExpressionWithType();
        result.expression = valueExpr;
        result.exprType = valueType;
        return result;
    }

    private static ExpressionWithType generateValueOfType(CedarType requiredType,
            EntityPool entities, SchemaWrapper schema) {

        if (randomChance(75) || requiredType.getTypeId() == CedarType.TypeId.BOOL) {
            // Crude but, hopefully, effective: just generate expressions until we get one with the right type.
            for (int i = 0; i < 20; i++) {
                ExpressionWithType attempt = generateValueExpr(entities, schema, false);
                if (attempt.exprType.equals(requiredType)) {
                    return attempt;
                }
            }
        }

        // Generate a literal of the required type:

        if (requiredType.getTypeId() == CedarType.TypeId.ENTITY) {
            Entity entity = entities.getRandomEntityOfType((CedarEntityRef)requiredType, random);
            if (entity != null) {
                ExpressionWithType result = new ExpressionWithType();
                result.expression = new EntityExpression(entity.getEntityId(),
                        Arrays.asList(entity.getEntityType()), null);
                result.exprType = requiredType;
                return result;
            }
        }
        else if (requiredType.getTypeId() == CedarType.TypeId.LONG) {
            int value = random.nextInt(100); // number from 0-99
            ExpressionWithType result = new ExpressionWithType();
            result.expression = new LongExpression(value, null);
            result.exprType = requiredType;
            return result;
        }
        else if (requiredType.getTypeId() == CedarType.TypeId.BOOL) {
            boolean value = (random.nextInt(2) == 0);
            ExpressionWithType result = new ExpressionWithType();
            result.expression = new BooleanExpression(value, null);
            result.exprType = requiredType;
            return result;
        }
        else if (requiredType.getTypeId() == CedarType.TypeId.RECORD) {
            ExpressionWithType result = new ExpressionWithType();
            result.expression = new RecordExpression(Collections.emptyMap(), null); // TODO generate field values
            result.exprType = requiredType;
            return result;
        }
        else if (requiredType.getTypeId() == CedarType.TypeId.STRING) {
            ExpressionWithType result = new ExpressionWithType();
            String stringValue = "string" + random.nextInt(30);
            result.expression = new StringExpression(stringValue, null);
            result.exprType = requiredType;
            return result;
        }

        throw new UnsupportedOperationException("Can't handle: " + requiredType.getTypeId().toString());
    }

    private static String generateCondition(EntityPool entities, SchemaWrapper schema) {
        String result;
        if (randomChance(50)) {
            result = "unless {\n";
        } else {
            result = "when {\n";
        }

        result += "    " + generateConditionExpression(entities, schema);
        result += "\n}";

        return result;
    }

    // TODO support multiple principal/resource types; combine with type tests ("is"/"has") to avoid errors
    private static Expression generateConditionExpression(EntityPool entities, SchemaWrapper schema) {
        // x in y
        // x == y (constant or other)
        // arithmetic:  x < y, x > y

        // 'principal', 'resource', 'action' -- refer to appropriate entity/action (entity reference)
        // 'context' -- refers to request context (record)

        ExpressionWithType combineValue = null;
        ExpressionWithType value;

        boolean skipBinOp;

        while (true) {
            value = generateValueExpr(entities, schema, false);

            skipBinOp = false;
            if (value.exprType.getTypeId() == CedarType.TypeId.BOOL) {
                if (randomChance(70)) {
                    // It's a boolean value so can be used as a condition:
                    if (randomChance(50))
                        skipBinOp = true;
                    else {
                        value.expression = new UnaryExpression(UnaryExpression.UnaryOp.Not,
                                value.expression, null);
                        skipBinOp = true;
                    }
                }
            }

            if (!skipBinOp) {
                // We now need a comparison or other operator, to another value of appropriate type
                ExpressionWithType otherValue;
                do {
                    otherValue = generateValueOfType(value.exprType, entities, schema);
                } while (value.expression.toString().equals(otherValue.expression.toString()));

                // TODO set membership ("in"), type tests ("is")

                BinaryExpression.BinaryOp operation = null;

                if (value.exprType.getTypeId() == CedarType.TypeId.LONG && randomChance(50)) {
                    // For numbers we can do relational comparisons as well as equality
                    int opIndex = random.nextInt(6);
                    switch (opIndex) {
                    case 0:
                        operation = BinaryExpression.BinaryOp.LessEq; break;
                    case 1:
                        operation = BinaryExpression.BinaryOp.Less; break;
                    case 2:
                        operation = BinaryExpression.BinaryOp.Eq; break;
                    case 3:
                        operation = BinaryExpression.BinaryOp.Neq; break;
                    case 4:
                        operation = BinaryExpression.BinaryOp.Greater; break;
                    case 5:
                        operation = BinaryExpression.BinaryOp.GreaterEq; break;
                    }
                }
                else {
                    int opIndex = random.nextInt(2);
                    switch (opIndex) {
                    case 0:
                        operation = BinaryExpression.BinaryOp.Eq; break;
                    case 1:
                        operation = BinaryExpression.BinaryOp.Neq; break;
                    }
                }

                value.expression = new BinaryExpression(value.expression, operation, otherValue.expression, null);
                value.exprType = CedarPrimitive.BOOL;
            }

            if (combineValue != null) {
                BinaryExpression.BinaryOp operation = null;
                int opIndex = random.nextInt(2);
                switch (opIndex) {
                case 0:
                    operation = BinaryExpression.BinaryOp.And; break;
                case 1:
                    operation = BinaryExpression.BinaryOp.Or; break;
                }
                value.expression = new BinaryExpression(combineValue.expression, operation, value.expression, null);
            }

            if (randomChance(75)) break;

            // On the next pass combine another boolean expression with the one we have now:
            combineValue = value;
        }

        return value.expression;
    }
}
