/*
 * This source file was generated by the Gradle 'init' task
 */
package uq.pac.rsvp;

import java.io.IOException;
import java.nio.file.Path;

import uq.pac.rsvp.policy.ast.policy.Policy;
import uq.pac.rsvp.policy.ast.policy.PolicyProgram;

public class Main {

    // Currently the app just accepts zero or more cedar policy file paths as
    // arguments which are parsed and the resulting policies and conditions printed
    // to stdout.
    public static void main(String[] args) throws IOException {

        // Parse each command line arg as a policy ast file
        for (String arg : args) {
            Path input = Path.of(arg).toAbsolutePath();
            PolicyProgram policies = PolicyProgram.parse(input);

            // Print it out
            System.out.println("file: " + input);

            int i = 1;
            for (Policy policy : policies.getPolicies()) {
                System.out.println("[" + i + "]    " + policy.toString());
                i++;
            }
        }
    }
}
