package uq.pac.childrenclinic.cedar;

import org.springframework.stereotype.Component;

@Component("cedarFormatter")
public class CedarFormatter {

	/**
	 * Applies specific HTML formatting rules to Cedar authorization logs. * @param text
	 * The raw log string.
	 * @return The HTML-formatted string.
	 */
	public String format(String text) {
		if (text == null || text.isBlank()) {
			return "";
		}

		// 1. Structural Replacements
		// Replaces the surrounded pipe character with a line break.
		text = text.replace(" | ", "<br/>");

		// Appends a line break after commas.
		text = text.replace("\",", ",<br/>");

		// Appends a line break after "Request:".
		text = text.replace("Request:", "Request:<br/>");

		// Resolves the hidden newline anomaly originating from CedarService text blocks.
		// The regex \\s* matches any whitespace character, including \n and \r.
		text = text.replaceAll("\\.\\s*Policy:", ".<br/>Policy:");

		// Normalizes any remaining hidden line breaks into HTML breaks.
		text = text.replaceAll("\\r?\\n", "<br/>");

		// Cleans up potential redundant line breaks generated by the combined rules.
		text = text.replace("<br/><br/>", "<br/>");

		// 2. Typographic Formatting (Bold)
		// Bolds specific keywords only when followed immediately by an equals sign.
		text = text.replaceAll("\\b(Principal|Action|Resource)\\b(?=\\s*=)", "<b>$1</b>");

		// Bolds "Policy" globally.
		text = text.replaceAll("\\b(Policy|Access Granted|Access Denied)\\b", "<b>$1</b>");

		// 3. Typographic Formatting (Underline)
		// Applies underline to specific request strings, accounting for injected line
		// breaks.
		text = text.replace("Page Request:<br/>", "<u>Page Request:</u><br/>");
		text = text.replace("Item Request:<br/>", "<u>Item Request:</u><br/>");
		text = text.replace("Response:", "<u>Response:</u>");

		return text;
	}

}
