DROP TABLE databases IF EXISTS;
DROP TABLE entities IF EXISTS;
DROP TABLE entity_types IF EXISTS;
DROP TABLE entity_databases IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE vet_specialties IF EXISTS;
DROP TABLE owners IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE visits IF EXISTS;

CREATE TABLE databases (
  database_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(30) UNIQUE NOT NULL
);
CREATE INDEX databases_name ON databases (name);

-- Super-Table.
CREATE SEQUENCE entities_sequence START WITH 1 INCREMENT BY 1;
CREATE TABLE entities (
  entity_id   INTEGER DEFAULT NEXT VALUE FOR entities_sequence PRIMARY KEY,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entity_types (
  entity_id   INT NOT NULL,
  entity_type VARCHAR(20) NOT NULL, -- 'User', 'Veterinarian', 'Owner', 'Pet', 'Visit'.
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);

CREATE TABLE entity_databases (
  entity_id INT NOT NULL,
  database_id INT NOT NULL,
  PRIMARY KEY (entity_id, database_id),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (database_id) REFERENCES databases(database_id) ON DELETE CASCADE
);

CREATE TABLE users (
  entity_id  INT PRIMARY KEY,
  username   VARCHAR(30) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX users_username ON users (username);

CREATE TABLE vets (
  entity_id  INT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name  VARCHAR(30) NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL,
  FOREIGN KEY (vet_id) REFERENCES vets(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

CREATE TABLE owners (
  entity_id  INT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name  VARCHAR(30) NOT NULL,
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE types (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE pets (
  entity_id  INT PRIMARY KEY,
  name       VARCHAR(30) NOT NULL,
  birth_date DATE NOT NULL,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id) REFERENCES owners(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE
);
CREATE INDEX pets_name ON pets (name);
ALTER TABLE pets ADD CONSTRAINT unique_pet UNIQUE (name, type_id, owner_id);

CREATE TABLE visits (
  entity_id   INT PRIMARY KEY,
  pet_id      INTEGER NOT NULL,
  visit_date  DATE NOT NULL,
  description VARCHAR(255),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (pet_id) REFERENCES pets(entity_id) ON DELETE CASCADE
);
CREATE INDEX visits_pet_id ON visits (pet_id);
