DROP TABLE databases IF EXISTS;
DROP TABLE entities IF EXISTS;
DROP TABLE entity_types IF EXISTS;
DROP TABLE entity_databases IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE vet_specialties IF EXISTS;
DROP TABLE roles IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE levels IF EXISTS;
DROP TABLE user_levels IF EXISTS;
DROP TABLE user_manager IF EXISTS;
DROP TABLE owners IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE confidentialities IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE pet_vets IF EXISTS;
DROP TABLE visit_vets IF EXISTS;

-- Lookup Databases Table.
CREATE TABLE databases (
  database_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(30) UNIQUE NOT NULL
);
CREATE INDEX databases_name ON databases (name);

-- Super-Table.
CREATE SEQUENCE entities_sequence START WITH 1 INCREMENT BY 1;
CREATE TABLE entities (
  entity_id   INTEGER DEFAULT NEXT VALUE FOR entities_sequence PRIMARY KEY,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entity_types (
  entity_id   INTEGER NOT NULL,
  entity_type VARCHAR(20) NOT NULL, -- 'User', 'Administrator', 'Secretary', 'Veterinarian', 'PetOwner', 'Pet', 'PetVisit'.
  PRIMARY KEY (entity_id, entity_type),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);

CREATE TABLE entity_databases (
  entity_id   INTEGER NOT NULL,
  database_id INTEGER NOT NULL,
  PRIMARY KEY (entity_id, database_id),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (database_id) REFERENCES databases(database_id) ON DELETE CASCADE
);

CREATE TABLE users (
  entity_id  INTEGER PRIMARY KEY,
  username   VARCHAR(30) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX users_username ON users (username);

CREATE TABLE vets (
  entity_id  INTEGER PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name  VARCHAR(30) NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX vets_last_name ON vets (last_name);

-- Lookup Specialties Table.
CREATE TABLE specialties (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL,
  PRIMARY KEY (vet_id, specialty_id),
  FOREIGN KEY (vet_id) REFERENCES vets(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

-- Lookup Employee Role Table.
CREATE TABLE roles (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX roles_name ON roles (name);

CREATE TABLE user_roles (
  user_id    INTEGER NOT NULL,
  role_id    INTEGER NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Lookup Professional Level Table.
CREATE TABLE levels (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX levels_name ON levels (name);

CREATE TABLE user_levels (
  user_id    INTEGER NOT NULL,
  level_id   INTEGER NOT NULL,
  PRIMARY KEY (user_id, level_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE
);

CREATE TABLE user_manager (
  user_id    INTEGER NOT NULL,
  manager_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, manager_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (manager_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  CONSTRAINT distinct_users CHECK (user_id != manager_id)
);

CREATE TABLE owners (
  entity_id  INTEGER PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name  VARCHAR(30) NOT NULL,
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX owners_last_name ON owners (last_name);

-- Lookup Types Table.
CREATE TABLE types (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE pets (
  entity_id  INTEGER PRIMARY KEY,
  name       VARCHAR(30) NOT NULL,
  birth_date DATE NOT NULL,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id) REFERENCES owners(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE,
  CONSTRAINT unique_pet UNIQUE (name, type_id, owner_id)
);
CREATE INDEX pets_name ON pets (name);

-- Lookup Types Table.
CREATE TABLE confidentialities (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80)
);
CREATE INDEX confidentialities_name ON types (name);

CREATE TABLE visits (
  entity_id          INTEGER PRIMARY KEY,
  pet_id             INTEGER NOT NULL,
  visit_date         DATE NOT NULL,
  confidentiality_id INTEGER NOT NULL,
  description VARCHAR(255),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (pet_id) REFERENCES pets(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (confidentiality_id) REFERENCES confidentialities(id) ON DELETE CASCADE
);
CREATE INDEX visits_pet_id ON visits (pet_id);

CREATE TABLE pet_vets (
  pet_id      INTEGER NOT NULL,
  vet_id      INTEGER NOT NULL,
  PRIMARY KEY (pet_id, vet_id),
  FOREIGN KEY (pet_id) REFERENCES pets(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (vet_id) REFERENCES vets(entity_id) ON DELETE CASCADE
);

CREATE TABLE visit_vets (
  visit_id    INTEGER NOT NULL,
  vet_id      INTEGER NOT NULL,
  PRIMARY KEY (visit_id, vet_id),
  FOREIGN KEY (visit_id) REFERENCES visits(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (vet_id) REFERENCES vets(entity_id) ON DELETE CASCADE
);
