DROP TABLE clinics IF EXISTS;
DROP TABLE entities IF EXISTS;
DROP TABLE entity_types IF EXISTS;
DROP TABLE entity_clinics IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE doctors IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE doctor_specialties IF EXISTS;
DROP TABLE roles IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE levels IF EXISTS;
DROP TABLE user_levels IF EXISTS;
DROP TABLE user_manager IF EXISTS;
DROP TABLE parents IF EXISTS;
DROP TABLE genders IF EXISTS;
DROP TABLE children IF EXISTS;
DROP TABLE confidentialities IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE child_doctors IF EXISTS;
DROP TABLE visit_doctors IF EXISTS;

-- Lookup Clinics Table.
CREATE TABLE clinics (
  clinic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR(30) UNIQUE NOT NULL
);
CREATE INDEX clinics_name ON clinics (name);

-- Super-Table.
CREATE SEQUENCE entities_sequence START WITH 1 INCREMENT BY 1;
CREATE TABLE entities (
  entity_id   INTEGER DEFAULT NEXT VALUE FOR entities_sequence PRIMARY KEY,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entity_types (
  entity_id   INTEGER NOT NULL,
  entity_type VARCHAR(20) NOT NULL, -- 'User', 'Administrator', 'Secretary', 'Doctor', 'Parent', 'Child', 'Visit'.
  PRIMARY KEY (entity_id, entity_type),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);

CREATE TABLE entity_clinics (
  entity_id   INTEGER NOT NULL,
  clinic_id   INTEGER NOT NULL,
  PRIMARY KEY (entity_id, clinic_id),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (clinic_id) REFERENCES clinics(clinic_id) ON DELETE CASCADE
);

CREATE TABLE users (
  entity_id  INTEGER PRIMARY KEY,
  username   VARCHAR(30) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX users_username ON users (username);

CREATE TABLE doctors (
  entity_id  INTEGER PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name  VARCHAR(30) NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX doctors_last_name ON doctors (last_name);

-- Lookup Specialties Table.
CREATE TABLE specialties (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE doctor_specialties (
  doctor_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL,
  PRIMARY KEY (doctor_id, specialty_id),
  FOREIGN KEY (doctor_id) REFERENCES doctors(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

-- Lookup Employee Role Table.
CREATE TABLE roles (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX roles_name ON roles (name);

CREATE TABLE user_roles (
  user_id    INTEGER NOT NULL,
  role_id    INTEGER NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Lookup Professional Level Table.
CREATE TABLE levels (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80) UNIQUE NOT NULL
);
CREATE INDEX levels_name ON levels (name);

CREATE TABLE user_levels (
  user_id    INTEGER NOT NULL,
  level_id   INTEGER NOT NULL,
  PRIMARY KEY (user_id, level_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE
);

CREATE TABLE user_manager (
  user_id    INTEGER NOT NULL,
  manager_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, manager_id),
  FOREIGN KEY (user_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (manager_id) REFERENCES users(entity_id) ON DELETE CASCADE,
  CONSTRAINT distinct_users CHECK (user_id != manager_id)
);

CREATE TABLE parents (
  entity_id  INTEGER PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name  VARCHAR(30) NOT NULL,
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20) UNIQUE NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE
);
CREATE INDEX parents_last_name ON parents (last_name);

-- Lookup Genders Table.
CREATE TABLE genders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80)
);
CREATE INDEX genders_name ON genders (name);

CREATE TABLE children (
  entity_id  INTEGER PRIMARY KEY,
  name       VARCHAR(30) NOT NULL,
  birth_date DATE NOT NULL,
  gender_id    INTEGER NOT NULL,
  parent_id   INTEGER NOT NULL,
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (parent_id) REFERENCES parents(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (gender_id) REFERENCES genders(id) ON DELETE CASCADE,
  CONSTRAINT unique_child UNIQUE (name, gender_id, parent_id)
);
CREATE INDEX children_name ON children (name);

-- Lookup Confidentialities Table.
CREATE TABLE confidentialities (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80)
);
CREATE INDEX confidentialities_name ON confidentialities (name);

CREATE TABLE visits (
  entity_id          INTEGER PRIMARY KEY,
  child_id             INTEGER NOT NULL,
  visit_date         DATE NOT NULL,
  confidentiality_id INTEGER NOT NULL,
  description VARCHAR(255),
  FOREIGN KEY (entity_id) REFERENCES entities(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (child_id) REFERENCES children(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (confidentiality_id) REFERENCES confidentialities(id) ON DELETE CASCADE
);
CREATE INDEX visits_child_id ON visits (child_id);

CREATE TABLE child_doctors (
  child_id      INTEGER NOT NULL,
  doctor_id      INTEGER NOT NULL,
  PRIMARY KEY (child_id, doctor_id),
  FOREIGN KEY (child_id) REFERENCES children(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (doctor_id) REFERENCES doctors(entity_id) ON DELETE CASCADE
);

CREATE TABLE visit_doctors (
  visit_id    INTEGER NOT NULL,
  doctor_id      INTEGER NOT NULL,
  PRIMARY KEY (visit_id, doctor_id),
  FOREIGN KEY (visit_id) REFERENCES visits(entity_id) ON DELETE CASCADE,
  FOREIGN KEY (doctor_id) REFERENCES doctors(entity_id) ON DELETE CASCADE
);
